[mgr]
show_hidden = true
show_symlink = true
ratio = [1, 6, 1]
sort = "natural"

[opener]
drawio = [
    { run = 'drawio "$@"', orphan = true, for = "unix" }
]

[open]
prepend_rules = [
    { name = "*.drawio", use="drawio"}
]

